---
- hosts: app
  roles:
    - { role: nginx, become: yes}
#    - role: nginx
#      become: yes
#      debugger: always
#      こういう書き方もできる
  tasks:
#    - name: view sample_word
#      debug:
#        var: sample_word
#      debugger: always
    - name: ip check
      shell: "ip a"
      register: result_ip
    - name: result_ip
      debug:
        var: "{{item}}"
      with_items:
        - result_ip.rc
        - result_ip.stdout
