---
- name: install_nginx
  apt:
    name: nginx
    state: present
  environment:
    RUNLEVEL: 1

- name: placement config file
  template:
    src: "{{trial_nginx}}_nginx.conf.j2"
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  register: result_nginx

- name: start nginx
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: view result_nginx
  debug:
    var: result_nginx

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
  when: result_nginx is changed
