source "https://rubygems.org"

# Include the Ruby Functions Framework as a dependency.
gem "functions_framework", "~> 0.5"
gem "google-cloud-storage"

# Other function dependencies, for example:
# gem "package", "~> version"

